

spring.application.name=childcare-backend
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/childcare_db
spring.datasource.username=childcare_user

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html